ALTER TABLE "AttendanceSession"
  ADD COLUMN IF NOT EXISTS "facultyId" TEXT,
  ADD COLUMN IF NOT EXISTS "department" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "semester" INTEGER,
  ADD COLUMN IF NOT EXISTS "course" TEXT,
  ADD COLUMN IF NOT EXISTS "section" TEXT,
  ADD COLUMN IF NOT EXISTS "mode" TEXT NOT NULL DEFAULT 'QR',
  ADD COLUMN IF NOT EXISTS "qrExpiresAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "endedAt" TIMESTAMP(3);

ALTER TABLE "AttendanceRecord"
  ALTER COLUMN "qrCode" DROP NOT NULL,
  ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'PRESENT',
  ADD COLUMN IF NOT EXISTS "mode" TEXT NOT NULL DEFAULT 'QR',
  ADD COLUMN IF NOT EXISTS "department" TEXT,
  ADD COLUMN IF NOT EXISTS "semester" INTEGER,
  ADD COLUMN IF NOT EXISTS "course" TEXT,
  ADD COLUMN IF NOT EXISTS "courseCode" TEXT,
  ADD COLUMN IF NOT EXISTS "scheduleId" TEXT,
  ADD COLUMN IF NOT EXISTS "markedById" TEXT,
  ADD COLUMN IF NOT EXISTS "markedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS "AttendanceRecord_userId_idx" ON "AttendanceRecord"("userId");
CREATE INDEX IF NOT EXISTS "AttendanceRecord_scheduleId_idx" ON "AttendanceRecord"("scheduleId");
CREATE INDEX IF NOT EXISTS "AttendanceRecord_department_semester_idx" ON "AttendanceRecord"("department", "semester");
