ALTER TABLE "AttendanceSession" ADD COLUMN IF NOT EXISTS "facultyId" TEXT;
ALTER TABLE "AttendanceSession" ADD COLUMN IF NOT EXISTS "department" TEXT DEFAULT '';
UPDATE "AttendanceSession" SET "department" = '' WHERE "department" IS NULL;
ALTER TABLE "AttendanceSession" ALTER COLUMN "department" SET NOT NULL;
ALTER TABLE "AttendanceSession" ADD COLUMN IF NOT EXISTS "semester" INTEGER;
ALTER TABLE "AttendanceSession" ADD COLUMN IF NOT EXISTS "course" TEXT;
ALTER TABLE "AttendanceSession" ADD COLUMN IF NOT EXISTS "section" TEXT;
ALTER TABLE "AttendanceSession" ADD COLUMN IF NOT EXISTS "mode" TEXT NOT NULL DEFAULT 'QR';
UPDATE "AttendanceSession" SET "mode" = 'QR' WHERE "mode" IS NULL OR "mode" = '';
ALTER TABLE "AttendanceSession" ALTER COLUMN "mode" SET DEFAULT 'QR';
ALTER TABLE "AttendanceSession" ALTER COLUMN "mode" SET NOT NULL;
ALTER TABLE "AttendanceSession" ADD COLUMN IF NOT EXISTS "qrExpiresAt" TIMESTAMP(3);
ALTER TABLE "AttendanceSession" ADD COLUMN IF NOT EXISTS "endedAt" TIMESTAMP(3);

ALTER TABLE "AttendanceRecord" ALTER COLUMN "qrCode" DROP NOT NULL;
ALTER TABLE "AttendanceRecord" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'PRESENT';
UPDATE "AttendanceRecord" SET "status" = 'PRESENT' WHERE "status" IS NULL OR "status" = '';
ALTER TABLE "AttendanceRecord" ALTER COLUMN "status" SET DEFAULT 'PRESENT';
ALTER TABLE "AttendanceRecord" ALTER COLUMN "status" SET NOT NULL;
ALTER TABLE "AttendanceRecord" ADD COLUMN IF NOT EXISTS "mode" TEXT NOT NULL DEFAULT 'QR';
UPDATE "AttendanceRecord" SET "mode" = 'QR' WHERE "mode" IS NULL OR "mode" = '';
ALTER TABLE "AttendanceRecord" ALTER COLUMN "mode" SET DEFAULT 'QR';
ALTER TABLE "AttendanceRecord" ALTER COLUMN "mode" SET NOT NULL;
ALTER TABLE "AttendanceRecord" ADD COLUMN IF NOT EXISTS "department" TEXT;
ALTER TABLE "AttendanceRecord" ADD COLUMN IF NOT EXISTS "academicYear" TEXT;
ALTER TABLE "AttendanceRecord" ADD COLUMN IF NOT EXISTS "year" INTEGER;
ALTER TABLE "AttendanceRecord" ADD COLUMN IF NOT EXISTS "semester" INTEGER;
ALTER TABLE "AttendanceRecord" ADD COLUMN IF NOT EXISTS "course" TEXT;
ALTER TABLE "AttendanceRecord" ADD COLUMN IF NOT EXISTS "subjectName" TEXT;
ALTER TABLE "AttendanceRecord" ADD COLUMN IF NOT EXISTS "courseCode" TEXT;
ALTER TABLE "AttendanceRecord" ADD COLUMN IF NOT EXISTS "facultyId" TEXT;
ALTER TABLE "AttendanceRecord" ADD COLUMN IF NOT EXISTS "facultyName" TEXT;
ALTER TABLE "AttendanceRecord" ADD COLUMN IF NOT EXISTS "room" TEXT;
ALTER TABLE "AttendanceRecord" ADD COLUMN IF NOT EXISTS "scheduleId" TEXT;
ALTER TABLE "AttendanceRecord" ADD COLUMN IF NOT EXISTS "markedById" TEXT;
ALTER TABLE "AttendanceRecord" ADD COLUMN IF NOT EXISTS "markedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS "AttendanceSession_scheduleId_idx" ON "AttendanceSession"("scheduleId");
CREATE INDEX IF NOT EXISTS "AttendanceSession_facultyId_idx" ON "AttendanceSession"("facultyId");
CREATE INDEX IF NOT EXISTS "AttendanceSession_startedById_idx" ON "AttendanceSession"("startedById");
CREATE INDEX IF NOT EXISTS "AttendanceSession_department_semester_idx" ON "AttendanceSession"("department", "semester");
CREATE INDEX IF NOT EXISTS "AttendanceRecord_userId_idx" ON "AttendanceRecord"("userId");
CREATE INDEX IF NOT EXISTS "AttendanceRecord_scheduleId_idx" ON "AttendanceRecord"("scheduleId");
CREATE INDEX IF NOT EXISTS "AttendanceRecord_department_semester_idx" ON "AttendanceRecord"("department", "semester");
CREATE INDEX IF NOT EXISTS "AttendanceRecord_academicYear_department_semester_idx" ON "AttendanceRecord"("academicYear", "department", "semester");
